name: Build and publish

on:
  push:
    branches: [ "main" ]

jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm i

    - name: Run TypeScript
      run: npx tsc

  publish:
    needs: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set version string
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Store version to a file
        run: echo "${{ steps.vars.outputs.sha_short }}" > ./version.txt

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push server container
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/livetrak-web:latest, ${{ secrets.DOCKERHUB_USERNAME }}/livetrak-web:${{ steps.vars.outputs.sha_short }}