name: Publish

on:
  push:
    tags:        
      - 'v[0-9]+.[0-9]+.[0-9]+'

publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set version string
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Store version to a file
        run: echo "${{ steps.vars.outputs.sha_short }}" > ./version.txt

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push server container
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true
          tags:
            - ${{ secrets.DOCKERHUB_USERNAME }}/livetrak-web:latest
            - ${{ secrets.DOCKERHUB_USERNAME }}/livetrak-web:${{ steps.vars.outputs.sha_short }}
            - ${{ secrets.DOCKERHUB_USERNAME }}/livetrak-web:${{ github.ref_name }}
